export const CHALLENGE_TEXTS = [
  "The quick brown fox jumps over the lazy dog",
  "Pack my box with five dozen liquor jugs",
  "How vexingly quick daft zebras jump",
  "Sphinx of black quartz judge my vow",
  "Waltz nymph for quick jigs vex Bud",
  "The five boxing wizards jump quickly",
  "Crazy Frederick bought many very exquisite opal jewels",
  "Jack amazed a few girls by dropping the antique onyx vase",
  "My girl wove six dozen plaid jackets before she quit",
  "Few black taxis drive up major roads on quiet hazy nights",
  "The job requires extra pluck and zeal from every young wage earner",
  "A quick movement of the enemy will jeopardize six gunboats",
  "Grumpy wizards make toxic brew for the evil queen and jack",
  "We promptly judged antique ivory buckles for the next prize",
  "Six big devils from Japan quickly forgot how to waltz",
  "Heavy boxes perform quick waltzes and jigs",
  "Crazy Fredrick bought many very exquisite opal jewels",
  "The wizard quickly jinxed the gnomes before they vaporized",
  "My faxed joke won a pager in the cable TV quiz show",
  "A mad boxer shot a quick gloved jab to the jaw of his dizzy opponent",
  "The public was amazed to view the quickness and dexterity of the juggler",
  "Jaded zombies acted quaintly but kept driving their oxen forward",
  "Sixty zippers were quickly picked from the woven jute bag",
  "Watch Jeopardy, Alex Trebek's fun TV quiz game",
  "Playing jazz vibe chords quickly excites my wife",
  "Five or six big jet planes zoomed quickly by the tower",
  "Both fickle dwarves jinx my pig quiz",
  "The five boxing wizards jump quickly through the night",
  "Sympathizing would fix Quaker objectives",
  "Many big jackdaws quickly zipped over the fox pen",
  "Jackdaws love my big sphinx of quartz",
  "The quick onyx goblin jumps over the lazy dwarf",
  "Bright vixens jump dozy fowl quicker than light",
  "Quick zephyrs blow vexing daft Jim",
  "Two driven jocks help fax my big quiz",
  "Five quacking zephyrs jolt my wax bed",
  "The job of waxing linoleum frequently peeves chintzy kids",
  "Junk MTV quiz graced by fox whelps",
  "Bawds jog flick quartz vex nymphs",
  "Quick wafting zephyrs vex bold Jim",
  "Quick blowing zephyrs vex daft Jim",
  "Sex charged fop blew my junk TV quiz",
  "Both fickle dwarves jinx my pig quiz",
  "Fat hag dwarves pack my box with five liquor jugs",
  "Five big quacking zephyrs jolt my wax bed",
  "The foxy diva wore my jasper necklace and quit the club",
  "Zany Greeks vow to fight my precious squid",
  "The brave knights jousted with six dozen wild oxen",
  "Six jumbo elephants quickly waved dozen flags",
  "Big July earthquakes confound zany experimental vow"
]
